### ISSUE TITLE
💡 [REQUEST] - Write Report Sections

### ISSUE THREAD

**Issue by izagorac** [philippedeb/susie#42]
### Description

This issue describes who works on what for the report:

1. Introduction (@merelanne)
2. Proposal (@merelanne)
2.1 Metrics (Everybody)
2.2 Guides (@izagorac)
3. Implementation (@philippedeb)
4. Validation
5. Social Impact (@Sebastien1999)
6. Conclusion (@philippedeb)
7. Discussion (Everybody)
8. Future Work (Everybody)

**Comment by merelanne** [comment]
Introduction is done, can someone review it please?

**Comment by merelanne** [comment]
I have finished most of my sections, waiting for feedback

**Comment by philippedeb** [comment]
Closed due to reaching the deadline; please refer to our Overleaf and handle all comments
